@hostname = http://localhost
@port = 3001
@jsonServerUrl = {{hostname}}:{{port}}
@contentType = application/json

###

# Get all entries
GET {{jsonServerUrl}}/entries HTTP/1.1
Content-Type: @contentType

###

# Get all entries between day x and day y
GET {{jsonServerUrl}}/entries/?createdAt_gte=2023-12-05T16:17:44.000Z&createdAt_lte=2023-12-29T16:17:44.000Z HTTP/1.1
Content-Type: @contentType

###

# Get all entries with all parent resources
GET {{jsonServerUrl}}/entries?_expand=type&_expand=account&_expand=category HTTP/1.1
Content-Type: @contentType

###

# Get all entries between day x and day y AND with all parent resources
GET {{jsonServerUrl}}/entries?_expand=type&_expand=account&_expand=category&createdAt_gte=2023-12-05T16:17:44.000Z&createdAt_lte=2023-12-29T16:17:44.000Z HTTP/1.1
Content-Type: @contentType

###

# Get all entries between day x and day y AND with all parent resources AND sort-by createdAt in ASC order
GET {{jsonServerUrl}}/entries?_expand=type&_expand=account&_expand=category&createdAt_gte=2023-12-05T16:17:44.000Z&createdAt_lte=2023-12-29T16:17:44.000Z&_sort=createdAt&_order=asc HTTP/1.1
Content-Type: @contentType

###

# Get entries aggregations
GET {{jsonServerUrl}}/entries/aggregations HTTP/1.1
Content-Type: @contentType

###

# Get entry id of 1
GET {{jsonServerUrl}}/entries/1 HTTP/1.1
Content-Type: @contentType

###

# Create a entry
POST {{jsonServerUrl}}/entries HTTP/1.1
Content-Type: @contentType

{
  "title": "Harry Potter"
}

###

# Update a entry
PUT {{jsonServerUrl}}/entries/1 HTTP/1.1
Content-Type: @contentType

{
  "title": "Dark Tower"
}

###

# Patch a entry
PATCH  {{jsonServerUrl}}/entries/1 HTTP/1.1
Content-Type: @contentType

{
  "title": "Dark Tower"
}

###

# Delete a entry
DELETE {{jsonServerUrl}}/entries/1 HTTP/1.1
Content-Type: @contentType

#########

# Get all repetitions
GET {{jsonServerUrl}}/categories HTTP/1.1
Content-Type: @contentType

#########

# Get all repeats
GET {{jsonServerUrl}}/repeats HTTP/1.1
Content-Type: @contentType

#########

# Get all categories
GET {{jsonServerUrl}}/categories HTTP/1.1
Content-Type: @contentType

###

# Get all catgories with entries
GET {{jsonServerUrl}}/categories?_embed=entries HTTP/1.1
Content-Type: @contentType

###

# Get category id of 1 own all entries
GET {{jsonServerUrl}}/categories/1/entries HTTP/1.1
Content-Type: @contentType