# Get all entries
GET http://localhost:3001/entries HTTP/1.1
Content-Type: application/json

###

# Get all entries with all parent resources
GET http://localhost:3001/entries?_expand=account&_expand=category HTTP/1.1
Content-Type: application/json

###

# Get entry id of 1
GET http://localhost:3001/entries/1 HTTP/1.1
Content-Type: application/json

###

# Create a entry
POST http://localhost:3001/entries HTTP/1.1
Content-Type: application/json

{
  "title": "Harry Potter"
}

###

# Update a entry
PUT http://localhost:3001/entries/1 HTTP/1.1
Content-Type: application/json

{
  "title": "Dark Tower"
}

###

# Patch a entry
PATCH  http://localhost:3001/entries/1 HTTP/1.1
Content-Type: application/json

{
  "title": "Dark Tower"
}

###

# Delete a entry
DELETE http://localhost:3001/entries/1 HTTP/1.1
Content-Type: application/json

#########

# Get all repetitions
GET http://localhost:3001/categories HTTP/1.1
Content-Type: application/json

#########

# Get all repeats
GET http://localhost:3001/repeats HTTP/1.1
Content-Type: application/json

#########

# Get all categories
GET http://localhost:3001/categories HTTP/1.1
Content-Type: application/json

###

# Get all catgories with entries
GET http://localhost:3001/categories?_embed=entries HTTP/1.1
Content-Type: application/json

###

# Get category id of 1 own all entries
GET http://localhost:3001/categories/1/entries HTTP/1.1
Content-Type: application/json